# Generated by Django 5.2.18 on 2026-10-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='商品名称')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='商品链接')),
                ('platform', models.CharField(default='AliExpress', max_length=40, verbose_name='平台')),
                ('shop', models.CharField(blank=True, max_length=200, verbose_name='店铺')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CollectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', '等待采集'), ('running', '采集中'), ('succeeded', '采集成功'), ('failed', '采集失败')], default='queued', max_length=12)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='market.product')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('product',), name='one_active_job_per_product')],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='价格')),
                ('currency', models.CharField(max_length=3, verbose_name='币种')),
                ('sales', models.PositiveIntegerField(blank=True, null=True, verbose_name='销量（来源提供时）')),
                ('observed_at', models.DateTimeField(verbose_name='观测时间')),
                ('source', models.CharField(choices=[('csv', 'CSV 导入'), ('web', '网页采集'), ('demo', '演示数据')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market.product')),
            ],
            options={
                'ordering': ['-observed_at', '-pk'],
                'indexes': [models.Index(fields=['product', 'observed_at'], name='market_snap_product_be3f7d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='snapshot_nonnegative_price'), models.UniqueConstraint(fields=('product', 'observed_at', 'source'), name='unique_observation')],
            },
        ),
    ]
