# Generated by Django 5.2.18 on 2026-10-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='context',
            field=models.CharField(blank=True, max_length=300, verbose_name='报价条件 / 规格'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='公开评分（5 分制）'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='公开评价数'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV 导入'), ('web', '网页采集'), ('demo', '演示数据'), ('manual', '手动记录公开页面')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 0), ('rating__lte', 5)), _connector='OR'), name='rating_zero_to_five'),
        ),
    ]
