# Generated by Django 5.2.18 on 2026-10-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_snapshot_context_snapshot_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Shopify 店铺首页')),
                ('status', models.CharField(choices=[('queued', '等待采集'), ('running', '采集中'), ('succeeded', '采集成功'), ('failed', '采集失败')], default='queued', max_length=12)),
                ('products', models.JSONField(default=list)),
                ('limited', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('url',), name='one_active_store_discovery')],
            },
        ),
    ]
