# Generated by Django 5.2.18 on 2026-10-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_storediscovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePriceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', '等待采集'), ('running', '采集中'), ('succeeded', '采集成功'), ('failed', '采集失败')], default='queued', max_length=12)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_jobs', to='market.storediscovery')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('discovery',), name='one_active_catalog_price_job')],
            },
        ),
    ]
