# Generated by Django 5.2.18 on 2026-10-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_storepricejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepricejob',
            name='indices',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='CatalogPriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('availability', models.CharField(blank=True, max_length=40)),
                ('observed_at', models.DateTimeField()),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='market.storediscovery')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='market.storepricejob')),
            ],
            options={
                'ordering': ['-observed_at', '-pk'],
                'indexes': [models.Index(fields=['discovery', 'url', 'observed_at'], name='market_cata_discove_b677d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'url'), name='one_catalog_quote_per_job'), models.CheckConstraint(condition=models.Q(('price_low__gte', 0), ('price_high__gte', models.F('price_low'))), name='catalog_quote_valid_range')],
            },
        ),
    ]
