# Generated by Django 5.2.18 on 2026-10-08 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_storepricejob_indices_catalogpriceobservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('store_url', models.URLField(max_length=500)),
                ('saved_item', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='选品备注')),
                ('stage', models.CharField(choices=[('research', '研究中'), ('priority', '重点关注'), ('paused', '暂不考虑')], default='research', max_length=12, verbose_name='研究状态')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.storediscovery')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'url'), name='one_candidate_per_owner_url')],
            },
        ),
    ]
