# Generated by Django 5.2.18 on 2026-10-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_catalogcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='storediscovery',
            name='analyze_prices',
            field=models.BooleanField(default=False),
        ),
    ]
