# Generated by Django 5.2.18 on 2026-10-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_storediscovery_analyze_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogpriceobservation',
            name='quote_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
