# Generated by Django 5.2.18 on 2026-10-08 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_catalogpriceobservation_quote_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('store_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('interval_hours', models.PositiveSmallIntegerField(choices=[(6, '每 6 小时'), (12, '每 12 小时'), (24, '每天一次')], default=24)),
                ('active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=12)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pending_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.storepricejob')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['active', 'next_run_at'], name='market_pric_active_74f165_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'url'), name='one_monitor_per_owner_url'), models.CheckConstraint(condition=models.Q(('interval_hours__in', [6, 12, 24])), name='monitor_safe_interval')],
            },
        ),
    ]
