# Generated by Django 5.2.18 on 2026-10-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_pricemonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('file_fingerprint', models.CharField(max_length=16)),
                ('samples', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_batch', to='market.snapshot')),
            ],
            options={
                'ordering': ['-snapshot__observed_at', '-pk'],
            },
        ),
    ]
