# Generated by Django 5.2.18 on 2026-10-08 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_productreviewbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='报价名称')),
                ('carrier', models.CharField(max_length=80, verbose_name='承运商 / 货代')),
                ('origin', models.CharField(max_length=2, verbose_name='始发国家 / 地区')),
                ('destination', models.CharField(max_length=2, verbose_name='目的国家 / 地区')),
                ('currency', models.CharField(max_length=3, verbose_name='报价币种')),
                ('method', models.CharField(choices=[('per_kg', '每公斤 + 每票'), ('first_step', '首重 + 续重')], max_length=12, verbose_name='计费方式')),
                ('min_weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='最低计费重（kg）')),
                ('max_weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='最高计费重（kg）')),
                ('step_weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='进位 / 续重单位（kg）')),
                ('per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='每公斤价格')),
                ('first_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='首重（kg）')),
                ('first_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='首重价格')),
                ('step_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='每续重单位价格')),
                ('fixed_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='每票固定费')),
                ('fuel_basis', models.CharField(choices=[('freight', '仅运输运价'), ('subtotal', '运输运价 + 每票固定费')], max_length=12, verbose_name='燃油费计费基数')),
                ('volume_divisor', models.PositiveIntegerField(blank=True, null=True, verbose_name='体积重系数（cm³/kg）')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='来源链接')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='货物 / 地区条件与费用说明')),
                ('source', models.CharField(choices=[('manual', '手动报价'), ('import', '表格导入')], max_length=10)),
                ('fingerprint', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'fingerprint'), name='unique_owner_shipping_rate'), models.CheckConstraint(condition=models.Q(('fixed_fee__gte', 0), ('max_weight__gte', models.F('min_weight')), ('min_weight__gt', 0), ('step_weight__gt', 0)), name='shipping_valid_weights_fee'), models.CheckConstraint(condition=models.Q(models.Q(('method', 'per_kg'), ('per_kg__gte', 0), ('per_kg__isnull', False)), models.Q(('first_price__gte', 0), ('first_price__isnull', False), ('first_weight__gt', 0), ('first_weight__isnull', False), ('method', 'first_step'), ('step_price__gte', 0), ('step_price__isnull', False)), _connector='OR'), name='shipping_valid_rate_method')],
            },
        ),
    ]
