# Generated by Django 5.2.18 on 2026-10-08 09:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_shippingrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-observed_at', '-pk']},
        ),
        migrations.AlterModelManagers(
            name='snapshot',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='snapshot',
            name='unique_observation',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='capture_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='capture_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV 导入'), ('web', '网页采集'), ('demo', '演示数据'), ('manual', '手动记录公开页面'), ('browser', '浏览器主动观测')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'browser'), _negated=True), fields=('product', 'observed_at', 'source'), name='unique_observation'),
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'browser')), fields=('owner', 'capture_id'), name='unique_browser_capture'),
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('capture_id__isnull', False), ('owner__isnull', False), ('source', 'browser')), models.Q(models.Q(('source', 'browser'), _negated=True), ('capture_id__isnull', True), ('owner__isnull', True)), _connector='OR'), name='snapshot_capture_ownership'),
        ),
    ]
