from django.urls import path
from . import views, workflow_views, price_history_views, price_monitoring_views, sample_market_views, otto_views, page_import_views, product_review_views
from . import shipping_views, browser_capture_views

urlpatterns = [
    path('browser/capture/download/', browser_capture_views.download, name='browser_capture_download'),
    path('browser/capture/', browser_capture_views.preview, name='browser_capture'),
    path('products/<int:pk>/browser/confirm/', browser_capture_views.confirm, name='browser_capture_confirm'),
    path('products/<int:pk>/browser/', browser_capture_views.report, name='browser_report'),
    path('tools/logistics/', shipping_views.logistics, name='shipping'),
    path('tools/logistics/rates/new/', shipping_views.rate_edit, name='shipping_rate_add'),
    path('tools/logistics/rates/<int:pk>/edit/', shipping_views.rate_edit, name='shipping_rate_edit'),
    path('tools/logistics/rates/<int:pk>/toggle/', shipping_views.rate_toggle, name='shipping_rate_toggle'),
    path('tools/logistics/import/', shipping_views.import_rates, name='shipping_import'),
    path('tools/logistics/template/<str:kind>/', shipping_views.template, name='shipping_template'),
    path('products/<int:pk>/reviews/', product_review_views.product_reviews, name='product_reviews'),
    path('import/page/', page_import_views.start_import, name='page_import_start'),
    path('products/<int:pk>/page/import/', page_import_views.import_page, name='page_import'),
    path('products/<int:pk>/otto/import/', otto_views.import_page, name='otto_import'),
    path('research/market/', sample_market_views.sample_market, name='sample_market'),
    path('monitoring/', price_monitoring_views.monitors, name='price_monitors'),
    path('monitoring/<int:pk>/toggle/', price_monitoring_views.toggle, name='monitor_toggle'),
    path('stores/<int:pk>/products/<int:index>/monitor/', price_monitoring_views.configure, name='monitor_config'),
    path('stores/<int:pk>/products/<int:index>/history/',price_history_views.catalog_history,name='catalog_history'),
    path('analysis/stores/<int:pk>/',workflow_views.store_analysis,name='store_analysis'),
    path('analysis/products/<int:pk>/',workflow_views.product_analysis,name='product_analysis'),
    path("candidates/", views.candidates, name="candidates"),
    path("candidates/compare/", views.candidate_compare, name="candidate_compare"),
    path("candidates/<int:pk>/edit/", views.candidate_edit, name="candidate_edit"),
    path("candidates/<int:pk>/archive/", views.candidate_archive, name="candidate_archive"),
    path("candidates/<int:pk>/restore/", views.candidate_restore, name="candidate_restore"),
    path("stores/<int:pk>/products/<int:index>/save/", views.candidate_add, name="candidate_add"),
    path("research/products/export/", views.catalog_export, name="catalog_export"),
    path("research/products/compare/", views.catalog_compare, name="catalog_compare"),
    path("research/products/", views.catalog_market, name="catalog_market"),
    path("stores/<int:pk>/products/<int:index>/refresh/", views.refresh_catalog_product, name="refresh_catalog_product"),
    path("stores/<int:pk>/products/<int:index>/", views.catalog_detail, name="catalog_detail"),
    path("research/", views.keyword_research, name="keyword_research"),
    path("stores/<int:pk>/research/", views.keyword_research, name="store_research"),
    path("stores/<int:pk>/prices/", views.collect_store_prices, name="collect_store_prices"),
    path("stores/discover/", views.discover_store, name="discover_store"),
    path("stores/", views.stores, name="stores"),
    path("collections/", views.collection_center, name="collection_center"),
    path("", views.dashboard, name="dashboard"),
    path("analyze/", views.analyze_competitor, name="analyze_competitor"),
    path("compare/", views.compare, name="compare"),
    path("products/<int:pk>/observe/", views.observation_add, name="observation_add"),
    path("products/add/", views.product_edit, name="product_add"),
    path("products/<int:pk>/", views.product_detail, name="product_detail"),
    path("products/<int:pk>/edit/", views.product_edit, name="product_edit"),
    path("products/<int:pk>/collect/", views.collect_product, name="collect_product"),
    path("products/<int:pk>/status/", views.job_status, name="job_status"),
    path("import/", views.csv_import, name="csv_import"),
    path("export/", views.csv_export, name="csv_export"),
    path("template/", views.csv_template, name="csv_template"),
    path("tools/profit/", views.profit, name="profit"),
]
